import 'lib/bootstrap'
import 'lib/swiper'
import 'components/usr/top-items/top-items.pc'
import 'components/usr/day-items/day-items.pc'
import 'components/usr/counter/counter.pc'
import 'components/usr/feel-top/feel-top.pc'
import 'components/usr/main-logo/main-logo.pc'
