version: '2'
services:
  mysql:
    image: mysql:5.6
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_DATABASE=comirepo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
  redis:
    image: redis:2.8
    ports:
      - "127.0.0.1:6379:6379"
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile.dev
    command: bin/rails s -P /dev/null
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - mysql
      - redis
      - webpacker
    environment: &rails_environment
      - DB_POOL=5
      - DB_HOST=mysql
      - DB_USER=root
      - DB_NAME=comirepo
      - SIDEKIQ_REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/home/rails/app
    depends_on:
      - webpacker
    stdin_open: true
    tty: true
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec sidekiq
    env_file:
      - .env
    links:
      - mysql
      - redis
    environment: *rails_environment
    volumes:
      - .:/home/rails/app
    stdin_open: true
    tty: true
  webpacker:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile.dev
    command: webpack -w
    volumes:
      - .:/home/rails/app
