version: '2'
services:
  mysql:
    image: mysql:5.6
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_DATABASE=comirepo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
  redis:
    image: redis:2.8
    ports:
      - "127.0.0.1:6379:6379"
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    links:
      - rails
    ports:
      - "80:80"
    environment:
      - RAILS_HOST=rails
      - RAILS_PORT=3000
      - S3_BUCKET=${AWS_BUCKET}
      - TARGET_DOMAIN=localhost
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile.dev
    command: bundle exec foreman start
    env_file:
      - .env
    ports:
      - 3000:3000
      - 3035:3035
    links:
      - mysql
      - redis
    environment: &rails_environment
      - DB_POOL=5
      - DB_HOST=mysql
      - DB_USER=root
      - DB_NAME=comirepo
      - SIDEKIQ_REDIS_URL=redis://redis:6379/0
      - SESSION_STORE=redis://redis:6379/1
      - CACHE_STORE=redis://redis:6379/2
      - SITE_URL=http://localhost:3000
      - PUMA_THREADS=2
    volumes:
      - .:/home/rails/app
    stdin_open: true
    tty: true
  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: ./docker/rails/Dockerfile.dev
  #   command: bundle exec sidekiq
  #   env_file:
  #     - .env
  #   links:
  #     - mysql
  #     - redis
  #   environment: *rails_environment
  #   volumes:
  #     - .:/home/rails/app
  #   stdin_open: true
  #   tty: true
  # webpacker:
  #   build:
  #     context: .
  #     dockerfile: ./docker/rails/Dockerfile.dev
  #   command: bin/webpack-dev-server
  #   ports:
  #     - 3035:3035
  #   volumes:
  #     - .:/home/rails/app
