version: '2'
services:
  mysql:
    image: mysql:5.6
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_DATABASE=comirepo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - mysql
    environment:
      - RAILS_ENV=production
      - DB_POOL=5
      - DB_HOST=mysql
      - DB_USER=root
      - DB_NAME=comirepo
      - DB_MIGRATE=true
      - SECRET_KEY_BASE=2fcf495ce43d469ebc2f489880fc729d63f6d852ae7ded00a3546e4da56761a62b3c45e0409332b98a91836318af0c311904dfe435972dca11ba1604efe4cd47
      - RAILS_SERVE_STATIC_FILES=true
    restart: always
