FROM node:8.5.0-alpine as node

FROM ruby:2.4.1-alpine3.6

RUN apk add --update --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del --purge tzdata

RUN mkdir -p /home/rails/app
WORKDIR /home/rails/app

# install nodejs yarn
COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/include/node /usr/local/include/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /opt/yarn /opt/yarn
RUN ln -s /usr/local/bin/node /usr/local/bin/nodejs && \
    ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm && \
    ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn

# install dependency package
# mariadb-dev for mysql
# execline for exec
RUN apk --update --no-cache add mariadb-dev tzdata execline

# bundle install
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && \
    apk --update --no-cache --virtual gem-builddeps add alpine-sdk && \
    bundle install --jobs=4

# yarn install
COPY package.json yarn.lock .postcssrc.yml ./
RUN yarn install
