:concurrency: 1
:schedule:
  collect:
    cron: '0 0 4 * * *'
    class: CollectWorker
  tweet_released:
    cron: '0 */10 0,7-23 * * *'
    class: TweetReleasedWorker
  tweet_free_last_date:
    cron: '0 */15 0,7-23 * * *'
    class: TweetFreeLastDateWorker
  tweet_registed:
    cron: '0 */10 0,7-23 * * *'
    class: TweetRegistedWorker
